### PR TITLE
Batch easy hard miner

### PR DESCRIPTION
**Pull request by marijnl**
EasyPositiveHardNegative miner called BatchEasyHardMiner

implementation based on https://github.com/littleredxh/EasyPositiveHardNegative and `BatchHardMiner

- `BatchEasyHardMiner` implementation is similar to `BatchHardMiner`. Actually, `BatchEasyHardMiner(positive_strategy=BatchEasyHardMiner.HARD, negative_strategy=BatchEasyHardMiner.HARD)` should be the same as `BatchHardMiner`
- `BatchEasyHardMiner` is configurable with a selection strategy eg `positive_strategy` and `negative_strategy`
- `BatchEasyHardMiner` limit min/max distances with `allowed_negative_range`
- simple unittest `test_batch-easy_hard_miner` that tests a few combinations of `BatchEasyHard` miners

### CODE REVIEW

**Comment by marijnl** [comment]
I forgot to sync KevinMusgrave:master with marijnl:master :(
Currently adapting code batch-easy-hard-miner in to master

**Comment by marijnl** [comment]
I'm having some trouble reproducing the error in unit-test, it runs fine in my env
It could be due to running on py37 instead of py38, but i'm not sure
I'll try to recreate the env that is used on the unit test machines

**Comment by KevinMusgrave** [comment]
Thanks for doing this! 😄 I will take a look hopefully tonight.

**Comment by littleredxh** [comment]
Hi Guys. Thank you for implement EPHN miner in this useful repo.

I go over the code in "src/pytorch_metric_learning/miners/batch_easy_hard_miner.py" and find a small problem. Line 49 to 55 does the same thing for positive and negative, which is not consistent with my original paper. 

I think it's our terminology problem. We refer Easy Positive(EP) as the positive with the closest distance to an anchor, and Hard Negative(HP) as the negative with the closest distance to an anchor. This may be misleading people to reimplement the idea. 

An easy to modify the code in "src/pytorch_metric_learning/miners/batch_easy_hard_miner.py" is to set initialization in Line 15 with "positive_strategy = HARD" and add a comment below to mention the "HARD" mode is consistent with the original paper

**Comment by marijnl** [comment]
Thanks for reviewing! Isn't this fixed by flipping the flag HARD flag to EASY on line 37?

**Comment by littleredxh** [comment]
If keep the function in line 49(get_mine_function()) and use Euclidean distance as the metric, then line 36 should be HARD and line 37 should be HARD too.

The modification should look like this
```
pos_func = self.get_mine_function(self.HARD if self.positive_strategy == self.EASY else self.EASY)
neg_func = self.get_mine_function(self.HARD)
```

**Comment by marijnl** [comment]
"We refer Easy Positive(EP) as the positive with the closest distance to an anchor "

When using Euclidean distances with the following mine function for positives
`pos_func = self.get_mine_function(self.HARD)`
It mines positives with the maximum distance to an anchor. 

Maybe you would be willing to take a look at `tests/miners/test_batch_easy_hard_miner.py` specifically `batch_easy_hard` to dubbelcheck my definition with a concrete example

**Comment by KevinMusgrave** [comment]
@littleredxh In the default mode (```positive_strategy = "easy", negative_strategy = "hard"```), it will do the following:

- With distance metrics like Euclidean distance (i.e. ```distance.is_inverted == False```)
  - Get the positive sample with minimum distance from each anchor
  - Get the negative sample with minimum distance from each anchor

- With similarity metrics like cosine similarity (i.e. ```distance.is_inverted == True```)
  - Get the positive sample with maximum similarity to each anchor
  - Get the negative sample with maximum similarity to each anchor

**Comment by marijnl** [comment]
Great additions @KevinMusgrave. Thanks

**Comment by KevinMusgrave** [comment]
Will merge later today

**Comment by KevinMusgrave** [comment]
I added "semihard" and "all" as options. The only disallowed combinations are ("semihard", "semihard") and ("semihard", "all"). 

Also it returns pairs (a1, p, a2, n) rather than triplets. BatchHardMiner still returns triplets.

I renamed and added some stats.

**Pull request merged**
