### PR TITLE
Faster custom label comparison

### PR DESCRIPTION
**Pull request by mlopezantequera**
Since the labels are numpy arrays, there's no need to loop over all labels. This can probably be even better if we expect the comparison function to be broadcastable (like np.equal), but this already helps a lot.

Added a new test case using floating point numbers that is easier to understand than the 2-dimensional ones.

### CODE REVIEW

**Comment by mlopezantequera** [comment]
@KevinMusgrave do you know what could be going on here? Seems unrelated to the PR

**Comment by KevinMusgrave** [comment]
There's occasionally random errors in some of the tests.

I should probably split the unit tests into different workflows so the entire thing doesn't have to be run again.

**Comment by KevinMusgrave** [comment]
Hmm weird, it happened again. I'll look into this later

**Comment by KevinMusgrave** [comment]
After I looked at your new test case, I found a bug (from a previous version) in the relevance mask computation.

It used to be:
```python
if label_comparison_fn is EQUALITY and embeddings_come_from_same_source:
    max_column -= 1
```

Now it's:
```python
if embeddings_come_from_same_source:
    max_column -= 1
```

**Pull request merged**
