### PR TITLE
DistributedLossWrapper enhancements

### LINKED ISSUE #701: arguments names are different in forward in when using the DDP wrapper
Hi,
Thank you for the great repository. I find it very useful. 

When using named arguments in the loss function, wrapping the loss with DDP results in a failure and produces the following error:

```python
TypeError: DistributedLossWrapper.forward() got an unexpected keyword argument 'embeddings'
```

Minimal example to reproduce:

```python
import torch
from pytorch_metric_learning.losses import CosFaceLoss

embeddings = torch.randn(3, 16)
labels = torch.LongTensor([0, 1, 2])
loss_fn = CosFaceLoss(num_classes=3, embedding_size=16)

loss = loss_fn(embeddings=embeddings, labels=labels)  # works 
print(loss)
```

And with the `DistributedLossWrapper`:

```diff
import torch
from pytorch_metric_learning.losses import CosFaceLoss
+ from pytorch_metric_learning.utils import distributed as pml_dist

embeddings = torch.randn(3, 16)
labels = torch.LongTensor([0, 1, 2])
loss_fn = CosFaceLoss(num_classes=3, embedding_size=16)
+ loss_fn = pml_dist.DistributedLossWrapper(loss_fn)

loss = loss_fn(embeddings=embeddings, labels=labels) # error
print(loss)
```

This behavior is somewhat inconvenient.

### PR DESCRIPTION
**Pull request by elisim**
fixes #701 

I've also added a warning when DistributedLossWrapper is being used in a non-distributed setting. Currently, an error is raised because of:

```python
world_size = torch.distributed.get_world_size()
```

### CODE REVIEW

**Comment by elisim** [comment]
@KevinMusgrave It appears that the test failures are unrelated to the PR.

**Comment by KevinMusgrave** [comment]
@elisim Thanks, I'll look into it

**Comment by elisim** [comment]
ping @KevinMusgrave :)

**Comment by KevinMusgrave** [comment]
Thanks @elisim !

**Pull request merged**
