### PR TITLE
Optimizes get_random_triplet_indices.

### PR DESCRIPTION
**Pull request by AlexSchuy**
Remedies #192. `get_random_triplet_indices` is now about 10-100 times faster than previous code, depending on input parameters. Let me know if there's anything I should change, or if there are additional tests you'd like me to add.

### CODE REVIEW

**Comment by KevinMusgrave** [comment]
Thanks this is great! Maybe it would be good to have a sanity check where you set ```weights``` to a one-hot vector for each row (i.e. 100% probability of picking a particular negative) and then make sure the retrieved triplets use only those negatives.

**Comment by AlexSchuy** [comment]
Okay, I added such a test. One issue with this test, however, is that when the code chooses an anchor that shares a label with the entry with a 1.0 weight, there is no valid negative sample, as the sum of the possible negative sample weights is 0. I modified the code to ignore these anchors and log a warning, but I'm not sure if you have a different approach in mind.

**Comment by KevinMusgrave** [comment]
Will this still work with ```DistanceWeightedMiner```? That miner needs ```weights``` to have number of rows equal to the batch size, i.e. each sample in the batch can have a different probability distribution of negatives.

**Comment by AlexSchuy** [comment]
Oh, sorry; I misunderstood the purpose of weights! I should have checked the previous behavior. I believe it is correct, now.

**Comment by KevinMusgrave** [comment]
I'll take a closer look on Wednesday

**Comment by KevinMusgrave** [comment]
@AlexSchuy I made some changes, mainly to support the usage of ```ref_labels```. Also got rid of some logic near the top of the function that I thought was unnecessary. Let me know if it still works for you and I'll merge the changes.

**Pull request merged**
